name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - marianfoo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: odata
    attributes:
      label: OData Version
      description: What OData Version are you using?
      options:
        - OData V2
        - OData V4
        - no OData Service related
    validations:
      required: true
  - type: dropdown
    id: draft
    attributes:
      label: Draft
      description: Are you using draft?
      options:
        - 'Yes'
        - 'No'
        - not relevant
    validations:
      required: true
  - type: input
    id: scenario
    attributes:
      label: Scenario
      description: In what Scenario are you using? (Fiori Elements, Freestyle)
    validations:
      required: true
  - type: input
    id: excelversion
    attributes:
      label: UI5 Excel Component
      description: What is your UI5 Excel Component Version?
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output, error popups or console errors. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: init
    attributes:
      label: Excel Component Init
      description: Please copy here how you initialize the ui5 component including all options.
      render: js
  - type: textarea
    id: manifest
    attributes:
      label: Manifest
      description: Please copy here the `resourceRoots` and `componentUsages` section of your manifest.json
      render: json
  - type: markdown
    attributes:
      value: |
        To make things easier for me, you can send me your metadata.xml with a link to this issue at marian@marianzeis.de
