on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      prs: ${{ steps.release.outputs.prs }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          command: manifest
          monorepo-tags: true
          release-type: node
      - name: log output
        run: |
          echo '${{toJSON(steps.release.outputs)}}'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        if: ${{ steps.release.outputs.releases_created }}
  
      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.17.1
        if: ${{ steps.release.outputs.releases_created }}

      - name: Run pnpm install
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm install  --no-frozen-lockfile

      - name: Build ui5-cc-excelupload
        run: pnpm --filter ui5-cc-excelupload build
        if: ${{ steps.release.outputs['packages/ui5-cc-excelUpload--release_created'] }}

      - name: Publish ui5-cc-excelupload to NPM
        if: ${{ steps.release.outputs['packages/ui5-cc-excelUpload--release_created'] }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo ":::: Publishing as $(npm whoami)"
          cd ./packages/ui5-cc-excelUpload/ && npm publish --provenance
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build ui5-cc-excelUpload-Button
        run: echo "Build ui5-cc-excelUpload-Button"
        if: ${{ steps.release.outputs['packages/ui5-cc-excelUpload-Button--release_created'] }}

      - name: Publish ui5-cc-excelUpload-Button to NPM
        if: ${{ steps.release.outputs['packages/ui5-cc-excelUpload-Button--release_created'] }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo ":::: Publishing as $(npm whoami)"
          cd ./packages/ui5-cc-excelUpload-Button/ && npm publish --provenance
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build ui5-cc-excelUpload-Generator
        run: echo "Build ui5-cc-excelUpload-Generator"
        if: ${{ steps.release.outputs['packages/ui5-cc-excelUpload-Generator--release_created'] }}

      - name: Publish ui5-cc-excelUpload-Generator to NPM
        if: ${{ steps.release.outputs['packages/ui5-cc-excelUpload-Generator--release_created'] }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo ":::: Publishing as $(npm whoami)"
          cd ./packages/ui5-cc-excelUpload-Generator/ && npm publish --provenance
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-prs:
    needs: release-please
    if: needs.release-please.outputs.prs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr: ${{ fromJSON(needs.release-please.outputs.prs) }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup git user
        run: |
          git config --global user.email "ops+robot@npmjs.com"
          git config --global user.name "npm team"
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Update PR ${{ matrix.pr.number }}
        if: ${{ matrix.pr }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW_TOKEN }}
        run: |
          gh pr checkout ${{ matrix.pr.number }}
          npm install
          npm run replaceString
          git add .
          git commit --amend --no-edit
          git push --force