on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ui5-cc-excelupload
          bump-minor-pre-major: true
          prerelease: true
      - uses: actions/checkout@v3
      - name: Setup git user
        run: |
          git config --global user.email "ops+robot@npmjs.com"
          git config --global user.name "npm team"
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Update versions
        if: ${{ steps.release.outputs.pr }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ fromJSON(steps.release.outputs.pr).number }}
          npm install
          npm run replaceString
          git add .
          git commit --amend --no-edit
          git push --force


      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        if: ${{ steps.release.outputs.release_created }}
      - name: Run npm install
        if: ${{ steps.release.outputs.release_created }}
        run: npm install

      - name: Build
        run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo ":::: Publishing as $(npm whoami)"
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
